version: '3'

services:
  food-manager:
    environment:
      - "SPRING_PROFILES_ACTIVE=mysql"
      - "MYSQL_HOST=mysql"
      - "RECEIPT_SERVICE_HOST=receipt"
    build:
      context: /order-manager
      dockerfile: Dockerfile
    depends_on:
      - mysql
    networks:
      - common-network
    ports:
      - 8080:8080
  receipt:
    build:
      context: /receipt-service
      dockerfile: Dockerfile
    depends_on:
      - food-manager
    networks:
      - common-network
    ports:
      - 8090:8090
  kitchen:
    build:
      context: /kitchen-service
      dockerfile: Dockerfile
    networks:
      - common-network
    ports:
      - 8070:8070
  kafka:
    image: apache/kafka:latest
    hostname: kafka
    restart: always
    networks:
      - common-network
    ports:
      - 9092:9092
  mysql:
    image: mysql:latest
    hostname: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: mydb
    ports:
      - 3306:3306
    networks:
      - common-network
    volumes:
      - mysql:/var/lib/mysql
volumes:
  mysql:

networks:
  common-network:
    driver: bridge