version: '3'

services:
  foodmanager:
    environment:
      - "POSTGRES_HOST=postgres"
    build:
      context: .
      dockerfile: food-manager/Dockerfile
    depends_on:
      - postgres
    networks:
      - common-network
    ports:
      - 8080:8080
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 12345
    ports:
      - 5432:5432
    networks:
      - common-network
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:

networks:
  common-network:
    driver: bridge