version: '3'

services:
  foodmanager:
    environment:
      - "SPRING_PROFILES_ACTIVE=mysql"
      - "MYSQL_HOST=mysql"
    build:
      context: .
      dockerfile: food-manager/Dockerfile
    depends_on:
      - mysql
    networks:
      - common-network
    ports:
      - 8080:8080
  mysql:
    image: mysql:latest
    hostname: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: mydb
    ports:
      - 3306:3306
    networks:
      - common-network
    volumes:
      - mysql:/var/lib/mysql
volumes:
  mysql:

networks:
  common-network:
    driver: bridge