version: '3'

services:

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 12345
    ports:
      - 5432:5432
    networks:
      - common-network
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:

networks:
  common-network:
    driver: bridge