version: '3'

services:
  food-manager:
    environment:
      - "POSTGRES_HOST=postgres"
      - "RECEIPT_SERVICE_HOST=receipt"
    build:
      context: /order-manager
      dockerfile: Dockerfile

    depends_on:
      - postgres
    networks:
      - common-network
    ports:
      - 8080:8080
  receipt:
    build:
      context: /receipt-service
      dockerfile: Dockerfile
    depends_on:
      - food-manager
    networks:
      - common-network
    ports:
      - 8090:8090
  kitchen:
    build:
      context: /kitchen-service
      dockerfile: Dockerfile
    networks:
      - common-network
    ports:
      - 8070:8070
  kafka:
    image: apache/kafka:latest
    hostname: kafka
    restart: always
    networks:
      - common-network
    ports:
      - 9092:9092
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 12345
    ports:
      - 5432:5432
    networks:
      - common-network
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:

networks:
  common-network:
    driver: bridge