server:
  port: 8090
spring:
  application:
    name: receipt-service
management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,auditevents"
        exclude: "env,beans,shutdown,mappings"
  server:
    port: 8093