server:
  port: 8070
spring:
  application:
    name: kitchen-service
  kafka:
    bootstrap-servers: ${KAFKA_HOST:localhost}:29092
    consumer:
      group-id: ${spring.application.name}-${kitchen.kafka.topic.in}
      key-deserializer: org.apache.kafka.common.serialization.IntegerDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            type:
              mapping: order-message:org.kitchen.dto.OrderMessage
    producer:
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring:
          json:
            type:
              mapping: kitchen-response:org.kitchen.dto.KitchenResponse

kitchen:
  kafka:
    topic:
      in: order-message
      out: kitchen-response

management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,auditevents"
        exclude: "env,beans,shutdown,mappings"
  server:
    port: 8094
