apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose --file docker-compose-postgres.yml convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: kitchen
  name: kitchen
spec:
  ports:
    - name: "8070"
      port: 8070
      targetPort: 8070
  selector:
    io.kompose.service: kitchen
