name: main

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Build and Run Tests
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven
      - name: Make maven wrapper script executable for Order Manager
        run: chmod +x ./order-manager/mvnw
      - name: Build order manager
        run: ./order-manager/mvnw -f order-manager/pom.xml package

      - name: Make maven wrapper script executable for Receipt Service
        run: chmod +x ./receipt-service/mvnw
      - name: Build receipt service
        run: ./receipt-service/mvnw -f receipt-service/pom.xml package

      - name: Make maven wrapper script executable for Kitchen Service
        run: chmod +x ./kitchen-service/mvnw
      - name: Build kitchen service
        run: ./kitchen-service/mvnw -f kitchen-service/pom.xml package

      - name: Publish test reports
        if: success() || failure()
        uses: scacap/action-surefire-report@v1
