name: main

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Build and Run Tests
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: maven
      - name: Make maven wrapper script executable for Order Manager
        run: chmod +x ./order-manager/mvnw
      - name: Build and run tests for Order Manager
        run: ./order-manager/mvnw -f order-manager/pom.xml package
      - name: Publish Order Manager test reports
        if: success() || failure()
        uses: scacap/action-surefire-report@v1

      - name: Make maven wrapper script executable for Receipt
        run: chmod +x ./receipt/mvnw
      - name: Build receipt project
        run: ./receipt/mvnw -f receipt/pom.xml package
      - name: Publish test reports
        if: success() || failure()
        uses: scacap/action-surefire-report@v1